#!/bin/bash

clear
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "LXC BOT INSTALLER"
echo "Made by Jikoz"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
cat << "EOF"
██╗██╗██╗  ██╗ ██████╗ █████╗█████
     ██║██║██║ ██╔╝██╔═══██╗╚══███╔╝
     ██║██║█████╔╝ ██║   ██║  ███╔╝ 
██   ██║██║██╔═██╗ ██║   ██║ ███╔╝  
╚█████╔╝██║██║  ██╗╚██████╔╝███████╗
 ╚════╝ ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
EOF

echo ""
echo "1) Install Install(config)"
echo "2) Install Install(Bot.py)"
echo "3) Exit"
echo ""
read -p "Select option [1-3]: " opt

case $opt in
  1)
    apt install python3-pip -y
    mkdir -p ~/.config/pip && echo -e "[global]\nbreak-system-packages = true" > ~/.config/pip/pip.conf
    sudo nano /etc/systemd/system/unixbot.service
[Unit]
Description=HizNodes Discord Bot
After=network.target

[Service]
User=root
WorkingDirectory=/root

# Environment Variables
Environment="PYTHONUNBUFFERED=1"
Environment="DISCORD_TOKEN=MTQ3MzY2NDA0NDE3NDAxNjcwOA.GnunAy.GPhraHb975OZ_bHaZlx857bMTji_sDIqVBlU4g"
Environment="MAIN_ADMIN_ID=1453621503731171358"

# Start Bot
ExecStart=/usr/bin/python3 /root/bot.py

# Auto-Restart
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
    ;;
  2)
    bash <(curl -s https://raw.githubusercontent.com/Trizer540/HvmPanel/refs/heads/main/panel)
    ;;
  3)
    exit 0
    ;;
  *)
    echo "❌ Invalid Option"
    sleep 1
    ;;
esac
done
